/*
# Seed KPI Dashboard Data

Inserts all 7 business areas, their KPIs with definitions/formulas/decisions,
sample current values with targets, monthly series, and breakdowns.
*/

-- ============================================================
-- AREAS
-- ============================================================
INSERT INTO areas (slug, name, icon, description, sort_order) VALUES
('ventas-0km', 'Ventas 0 km', 'Car', 'Vehículos nuevos: cumplimiento, conversión, margen y productividad comercial.', 1),
('plan-rombo', 'Plan Rombo', 'TrendingUp', 'Suscripciones, cartera, adjudicaciones y aporte económico del plan de ahorro.', 2),
('mi-auto-ya', 'Mi Auto Ya!', 'RefreshCw', 'Usados: compra, peritaje, preparación, rotación de stock y venta.', 3),
('postventa', 'Postventa', 'Wrench', 'Taller, repuestos, stock, agenda y cumplimiento de compras a Renault.', 4),
('calidad', 'Calidad', 'ShieldCheck', 'Mystery Shopping, NPS, DDA, OCV, Hot Alert e incentivos de calidad.', 5),
('rrhh', 'Recursos Humanos', 'Users', 'Ausentismo, rotación, costo de personal y gestión disciplinaria.', 6),
('admn-finanzas', 'Administración y Finanzas', 'Landmark', 'Liquidez, endeudamiento, rentabilidad, costos y créditos a cobrar.', 7)
ON CONFLICT (slug) DO NOTHING;

-- Helper: get area IDs
DO $$ DECLARE
  v_ventas uuid; v_rombo uuid; v_miauto uuid; v_postv uuid; v_calidad uuid; v_rrhh uuid; v_finan uuid;
BEGIN
  SELECT id INTO v_ventas FROM areas WHERE slug = 'ventas-0km';
  SELECT id INTO v_rombo FROM areas WHERE slug = 'plan-rombo';
  SELECT id INTO v_miauto FROM areas WHERE slug = 'mi-auto-ya';
  SELECT id INTO v_postv FROM areas WHERE slug = 'postventa';
  SELECT id INTO v_calidad FROM areas WHERE slug = 'calidad';
  SELECT id INTO v_rrhh FROM areas WHERE slug = 'rrhh';
  SELECT id INTO v_finan FROM areas WHERE slug = 'admn-finanzas';

  -- VENTAS 0 KM
  INSERT INTO kpis (area_id, name, definition, formula, decision, unit, target_direction, sort_order) VALUES
  (v_ventas, 'Cumplimiento del objetivo comercial y ritmo diario', 'Mide el avance hacia los patentamientos requeridos por fábrica. Distingue boletos, facturación, documentación en gestión, unidades en manos del gestor, patentamientos y entregas.', 'Patentamientos reconocidos ÷ objetivo vigente × 100. Ritmo pendiente = unidades faltantes ÷ días hábiles restantes.', 'Acelerar ventas y trámites que condicionan el cierre; anticipar la escala de Prima Volumen.', '%', 'up', 1),
  (v_ventas, 'Conversión de leads y efectividad por canal y punto de venta', 'Integra el embudo desde el ingreso/asignación del lead hasta la venta; muestra etapas abiertas y motivos de pérdida.', 'Ventas de una cohorte ÷ leads de esa cohorte × 100, por origen, punto y vendedor.', 'Mejorar seguimiento, distribución de oportunidades e inversión comercial sin ocultar leads fallidos.', '%', 'up', 2),
  (v_ventas, 'Margen de contribución por unidad y total', 'Mide el aporte económico de la operación después de descuentos y costos variables; conserva el desglose de bonificación de fábrica y concesionaria.', 'Venta neta + reintegros no incluidos − costo de reposición − costos variables directos.', 'Definir descuentos, modelos prioritarios y operaciones que necesitan autorización por margen.', '$', 'up', 3),
  (v_ventas, 'Productividad comercial por vendedor', 'Muestra cuánto vende cada vendedor, con qué conversión, contribución y seguimiento de oportunidades.', 'Unidades por vendedor y cumplimiento de su objetivo; contribución generada y conversión de su cohorte de leads como desgloses.', 'Asignar objetivos y oportunidades, identificar necesidades de capacitación y evaluar resultados comparables.', 'u.', 'up', 4),
  (v_ventas, 'Productividad comercial por modelo', 'Completa la apertura por modelo y versión para identificar qué productos sostienen volumen y contribución.', 'Unidades por modelo ÷ objetivo asignado al modelo × 100; participación en ventas y contribución total/media por modelo.', 'Ajustar oferta, campañas y asignación de stock; no confundir un modelo de alto volumen con uno rentable.', '%', 'up', 5),
  (v_ventas, 'Composición de la venta', 'Identifica la participación de contado, toma de usado y crédito, incluyendo operaciones con modalidades combinadas.', 'Operaciones por modalidad ÷ operaciones totales × 100. Categorías exclusivas: contado, permuta, crédito y combinaciones.', 'Evaluar dependencia del crédito, ingreso de usados y necesidades de fondos de cada modalidad.', '%', 'up', 6),
  (v_ventas, 'Autos peritados vs. tomados por vendedor', 'Mide la conversión de usados ofrecidos en parte de pago en unidades efectivamente tomadas, vinculadas al vendedor de 0 km.', 'Vehículos tomados ÷ vehículos peritados de la misma cohorte × 100, por vendedor.', 'Detectar operaciones perdidas por tasación y coordinar condiciones de toma con Mi Auto Ya! sin duplicar vehículos.', '%', 'up', 7),
  (v_ventas, 'Brecha de posicionamiento de precios', 'Compara precios propios con referencias equivalentes por modelo, versión, equipamiento y condición de pago.', '(Precio de cierre propio − precio de referencia) ÷ precio de referencia × 100.', 'Revisar bonificaciones y fundamentar decisiones de precio sin separar competitividad de contribución.', '%', 'down', 8),
  (v_ventas, 'Cumplimiento y tiempo de entrega', 'Mide el plazo desde boleto hasta entrega y el cumplimiento de la fecha prometida; identifica demoras de documentación y preparación.', 'Entregas en fecha ÷ entregas totales × 100; días promedio por etapa y operaciones abiertas vencidas.', 'Coordinar Secretaría Comercial, gestoría y preparación antes de incumplir la promesa al cliente.', '%', 'up', 9),
  (v_ventas, 'Participación de mercado en Tucumán', 'Sitúa el desempeño de Renault y de Ruiz Automotores frente al mercado provincial y su evolución.', 'Patentamientos de la marca o del concesionario ÷ patentamientos del mercado comparable × 100.', 'Distinguir contracción del mercado de pérdida propia de participación y contextualizar el objetivo de fábrica.', '%', 'up', 10);

  -- PLAN ROMBO
  INSERT INTO kpis (area_id, name, definition, formula, decision, unit, target_direction, sort_order) VALUES
  (v_rombo, 'Cumplimiento del objetivo de suscripciones', 'Mide las suscripciones aceptadas frente al objetivo mensual comunicado por Plan Rombo y la escala de incentivo que corresponda.', 'Suscripciones aceptadas ÷ objetivo mensual × 100; avance diario y apertura por vendedor y punto de venta.', 'Corregir el ritmo comercial y anticipar el efecto de alcanzar o perder un escalón de incentivo.', '%', 'up', 1),
  (v_rombo, 'Contribución económica mensual', 'Integra ingresos por suscripción, mantenimiento de cartera, débito y entrega, menos comisiones y costos directos.', 'Ingresos atribuibles − comisiones − costos directos. Resultado devengado y flujo percibido por separado.', 'Evaluar el aporte de la unidad y explicar la diferencia entre producción, incentivos generados y cobros.', '$', 'up', 2),
  (v_rombo, 'Cartera activa y tasa de caída por cohorte', 'Muestra la permanencia de contratos del mismo período de origen a medida que avanzan las cuotas.', 'Contratos activos en cuota n ÷ contratos iniciales de la cohorte × 100; caída = 100% − tasa activa.', 'Identificar campañas o vendedores con mayor caída y proteger los ingresos futuros de cartera.', '%', 'up', 3),
  (v_rombo, 'Cobertura de contacto del call center', 'Distingue intentos de contacto de conversaciones efectivas con clientes convocados a licitar.', 'Clientes con intento registrado ÷ asignados × 100; clientes contactados efectivamente ÷ asignados × 100.', 'Distribuir carga y mejorar cobertura y calidad de contacto dentro de la ventana de cada acto.', '%', 'up', 4),
  (v_rombo, 'Conversión de invitaciones, ofertas y adjudicaciones', 'Expone el embudo de convocados, contactados, ofertas, adjudicaciones y entregas, con cantidades en cada etapa.', 'Ofertas ÷ contactos efectivos; adjudicaciones ÷ ofertas; entregas ÷ adjudicaciones × 100.', 'Evaluar guiones y seguimiento, identificar el punto de pérdida y aumentar la efectividad de las licitaciones.', '%', 'up', 5),
  (v_rombo, 'Productividad comisional por vendedor y punto de venta', 'Relaciona producción, comisiones generadas y aporte al negocio.', 'Suscripciones por vendedor ÷ objetivo × 100; comisiones generadas y comparación con su remuneración básica.', 'Revisar producción, concentración y esquema comisional; evitar evaluar sólo cantidad de contratos.', '%', 'up', 6),
  (v_rombo, 'Conversión y rentabilidad de leads', 'Completa la conversión y el retorno de las oportunidades obtenidas con inversión identificable.', 'Suscripciones de la cohorte ÷ leads atribuibles × 100. Retorno = (contribución atribuible antes de captación − inversión) ÷ inversión × 100.', 'Reasignar inversión entre canales considerando costos y permanencia de los contratos, no sólo ingresos brutos.', '%', 'up', 7),
  (v_rombo, 'Resolución administrativa y escalamiento', 'Mide cierre de trámites, demora, casos pendientes y escalamiento al nivel gerencial.', 'Casos vencibles en el período cerrados dentro del plazo ÷ casos vencibles × 100; días por caso y escalaciones no justificadas ÷ escalaciones totales.', 'Resolver en el nivel adecuado, reducir burocracia y reservar a la Gerencia para los casos críticos.', '%', 'up', 8),
  (v_rombo, 'Ciclo de adjudicación y entrega', 'Descompone la demora total en documentación interna, firma, facturación de terminal, arribo, patentamiento y entrega.', 'Fecha de fin − fecha de inicio de cada etapa. Mostrar por separado tiempos internos, de terminal y de otros terceros.', 'Actuar sobre tramos controlables y respaldar reclamos sin atribuir al equipo toda demora externa.', 'días', 'down', 9);

  -- MI AUTO YA!
  INSERT INTO kpis (area_id, name, definition, formula, decision, unit, target_direction, sort_order) VALUES
  (v_miauto, 'Cumplimiento del objetivo de unidades', 'Mide las unidades entregadas y cobradas frente al objetivo interno aprobado para Mi Auto Ya!, sin trasladar una meta de fábrica.', 'Unidades entregadas y cobradas ÷ objetivo interno mensual × 100. Desglosar boletos, entregas y cobranzas pendientes.', 'Ajustar ritmo comercial y capacidad de cierre; identificar la etapa que frena el cumplimiento.', '%', 'up', 1),
  (v_miauto, 'Contribución económica total y por unidad', 'Mide el aporte de la venta después de adquisición o consignación, reacondicionamiento y costos variables.', 'Venta neta − costo de adquisición/consignación − reacondicionamiento − comisiones − otros costos variables atribuibles.', 'Definir condiciones de toma, precios y prioridades de salida; explicar el aporte de cada vehículo.', '$', 'up', 2),
  (v_miauto, 'Composición de la venta', 'Distingue contado, permuta de usado, crédito y operaciones que combinan modalidades.', 'Operaciones por modalidad ÷ operaciones totales × 100.', 'Evaluar generación de caja, necesidad de financiación e ingreso de nuevas unidades por permuta.', '%', 'up', 3),
  (v_miauto, 'Conversión de leads', 'Muestra oportunidades ingresadas, gestionadas, perdidas y cerradas, por origen y vendedor.', 'Ventas cerradas ÷ leads de la misma cohorte × 100. Identificar no contactados, inválidos, duplicados y motivos de pérdida.', 'Mejorar seguimiento y distribución de consultas; evaluar los canales de captación con datos comparables.', '%', 'up', 4),
  (v_miauto, 'Autos peritados vs. tomados por peritador', 'Mide la efectividad de las evaluaciones realizadas por cada peritador para incorporar vehículos al negocio.', 'Vehículos tomados ÷ vehículos peritados de la misma cohorte × 100, por peritador.', 'Revisar criterios de tasación y aceptación; contrastar efectividad con margen y desvío posterior de reparación.', '%', 'up', 5),
  (v_miauto, 'Antigüedad y rotación del stock', 'Mide permanencia de unidades abiertas y velocidad de salida de las vendidas, desde recepción/peritaje y alta.', 'Días en stock por vehículo; promedio de días hasta venta y entrega; participación del stock con más de 60/90 días.', 'Acelerar publicación, preparación o salida y evitar unidades que consumen recursos sin rotar.', 'días', 'down', 6),
  (v_miauto, 'Productividad por vendedor', 'Relaciona unidades, participación en ventas, contribución y comisiones generadas por vendedor.', 'Unidades y contribución por vendedor; participación sobre total; conversión y comisión generada frente a su básico.', 'Capacitar y evaluar desempeño; registrar por separado operaciones frustradas y sus causas.', 'u.', 'up', 7),
  (v_miauto, 'Tiempo desde recepción/peritaje hasta publicación', 'Mide la demora hasta que la unidad está revisada, documentada, fotografiada y disponible para ofrecer.', 'Fecha/hora de publicación o disponibilidad − fecha/hora de recepción.', 'Evitar vehículos fuera de la oferta comercial por falta de preparación, documentación o carga.', 'días', 'down', 8),
  (v_miauto, 'Tiempo de preparación y entrega en fecha', 'Mide los circuitos paralelos de servicio y gestoría desde el boleto hasta la entrega.', 'Días desde boleto hasta vehículo listo; entregas en fecha comprometida ÷ entregas totales × 100.', 'Coordinar mecánica, carrocería, repuestos y documentación; cumplir la promesa de entrega.', '%', 'up', 9);

  -- POSTVENTA
  INSERT INTO kpis (area_id, name, definition, formula, decision, unit, target_direction, sort_order) VALUES
  (v_postv, 'Entradas al taller por día', 'Mide el volumen de vehículos que ingresan físicamente al taller, separado por sede y tipo de trabajo.', 'Conteo de ingresos diarios vinculados a órdenes de reparación; acumulado mensual y promedio por día operativo.', 'Detectar caída de actividad, ajustar agenda y campañas y dimensionar capacidad disponible.', 'u/día', 'up', 1),
  (v_postv, 'Productividad y utilización de la capacidad del taller', 'Relaciona horas vendidas, presencia disponible y trabajo efectivo.', 'Productividad = horas facturadas ÷ disponibles × 100; utilización = horas trabajadas ÷ disponibles × 100.', 'Identificar si la pérdida está en demanda, tiempos muertos o rendimiento; analizar especialistas por separado.', '%', 'up', 2),
  (v_postv, 'Ciclo de vida de órdenes de trabajo', 'Mide duración y envejecimiento de las órdenes, por asesor, etapa y tipo de intervención.', 'Fecha/hora de cierre − apertura; promedio/mediana y cantidad de órdenes abiertas fuera del plazo acordado.', 'Resolver demoras, ordenar la carga de asesores y anticipar vehículos detenidos y reclamos.', 'días', 'down', 3),
  (v_postv, 'Reparación correcta a la primera', 'Control interno de retornos, retrabajos y garantías internas atribuibles a la misma causa.', 'Órdenes con retrabajo atribuible ÷ órdenes cerradas de la base definida × 100.', 'Corregir causas técnicas y control final, sin premiar productividad a costa de calidad.', '%', 'down', 4),
  (v_postv, 'Efectividad de la agenda', 'Muestra la ocupación programada y la asistencia real de los turnos, diferenciadas de la utilización del mecánico.', 'Horas agendadas ÷ capacidad disponible × 100; inasistencias ÷ turnos agendados × 100.', 'Ajustar confirmaciones y captación; evitar una agenda llena que no se transforme en entradas reales.', '%', 'up', 5),
  (v_postv, 'Ventas y margen por familia, mano de obra y canal', 'Mide repuestos y servicios por familia y por mostrador, taller interno y e-commerce/Mercado Libre.', 'Ventas netas − costo de reposición/directo; margen ÷ ventas netas × 100.', 'Orientar compras y acciones comerciales; distinguir canales de alto volumen de los que aportan margen.', '$', 'up', 6),
  (v_postv, 'Stock Vivo, Durmiente y Muerto; rotación', 'Expone valor y participación de cada categoría, sin convertir automáticamente stock antiguo en pérdida contable.', 'Valor por categoría ÷ inventario total × 100; rotación = costo vendido del período ÷ inventario promedio.', 'Sincerar existencia, definir salida o recuperación y evitar reposición de piezas sin demanda.', '%', 'up', 7),
  (v_postv, 'Cumplimiento de compras de repuestos a Renault', 'Mide el objetivo mensual y su regularidad con pedidos a valor PNC en estados admitidos por Renault.', 'Pedidos facturados, asignados o de entrega directa ÷ objetivo PNC × 100. Excluir herramientas, equipos, publicidad y mobiliario.', 'Anticipar incumplimientos e incentivos; planificar compras sin aumentar stock inmovilizado innecesario.', '%', 'up', 8),
  (v_postv, 'Exactitud y trazabilidad de inventario', 'Compara existencia física y sistema, y el respaldo oportuno de cada movimiento.', 'Ítems coincidentes ÷ ítems auditados × 100; movimientos documentados ÷ movimientos revisados × 100.', 'Prevenir faltantes y demoras por stock incorrecto; dar respaldo al sinceramiento del inventario.', '%', 'up', 9),
  (v_postv, 'Nivel de servicio de abastecimiento y e-commerce', 'Mide disponibilidad, precisión y velocidad para abastecer taller y preparar pedidos digitales.', 'Solicitudes completas y a tiempo ÷ solicitudes totales × 100; errores y tiempo de preparación como desgloses.', 'Evitar técnicos detenidos y devoluciones; acompañar la venta digital con despacho confiable.', '%', 'up', 10);

  -- CALIDAD
  INSERT INTO kpis (area_id, name, definition, formula, decision, unit, target_direction, sort_order) VALUES
  (v_calidad, 'Mystery Shopping', 'Mide el resultado de cliente incógnito con dos aperturas independientes: Ventas y Postventa.', 'Promedio Lead y Call.', 'Proteger las llaves de cobro y corregir el canal o punto que reduce el resultado.', '%', 'up', 1),
  (v_calidad, 'Índice VoC NPS: VN y PV', 'Evalúa satisfacción mediante la ponderación de tres preguntas. Promotores: 5 estrellas; neutros: 4; detractores: 1, 2 y 3.', 'NPS por pregunta = (promotores − detractores) ÷ encuestas × 100. Index = 50% general + 25% segunda + 25% tercera. Objetivo: ≥85.', 'Priorizar causas de insatisfacción que afectan resultados e incentivos, sin usar sólo el porcentaje de cinco estrellas.', '%', 'up', 2),
  (v_calidad, 'DDA: Recepción y Preparación', 'Mide uso de DDA con dos bases distintas de vehículos; cada proceso pesa 10% en la Prima Calidad Comercial.', 'Recepción = VIN con recepción DDA ÷ VIN asignados con fecha ARA × 100. Preparación = VIN con preparación DDA ÷ VIN con entrega administrativa global × 100. Objetivo: ≥85%.', 'Asegurar registros que habilitan incentivos de proceso, sujetos a Hot Alert; no promediar etapas indiscriminadamente.', '%', 'up', 3),
  (v_calidad, 'OCV Battery Check', 'Control de batería con útil CLIP en preparación previa a entrega.', 'VIN con OCV válido ÷ VIN de la base oficial evaluada × 100. Objetivo ≥85%.', 'Detectar VIN sin control válido y preservar el incentivo OCV, condicionado por Hot Alert.', '%', 'up', 4),
  (v_calidad, 'Hot Alert: gestión y cierre', 'Alertas por satisfacción general de 3 estrellas o menos.', 'Días desde generación hasta cierre; alertas abiertas, vencidas y cerradas por plazo.', 'Priorizar casos que pueden bloquear DDA y OCV; no asumir que un promedio de tiempos habilita la llave.', 'días', 'down', 5),
  (v_calidad, 'Incentivos de Calidad: habilitados, cobrados y en riesgo', 'Traduce el desempeño a dinero, separado entre Prima Calidad Comercial y animación Calidad de Postventa.', 'Estimación = Σ(base elegible validada × tasa publicada por componente). Exponer estimado, informado, facturado, cobrado, retenido y en riesgo.', 'Priorizar la brecha de mayor impacto económico y controlar reconsideraciones y recuperos sin anticipar cobros.', '$', 'up', 6);

  -- RRHH
  INSERT INTO kpis (area_id, name, definition, formula, decision, unit, target_direction, sort_order) VALUES
  (v_rrhh, 'Tasa de ausentismo', 'Mide la capacidad laboral perdida por ausencias justificadas e injustificadas y permite identificar recurrencia por área.', 'Horas o días de ausencia ÷ horas o días laborables planificados × 100.', 'Planificar dotación, cubrir puestos críticos y actuar sobre ausentismo recurrente.', '%', 'down', 1),
  (v_rrhh, 'Tasa de llegadas tarde y reincidencia', 'Mide ingresos posteriores al horario y la proporción de empleados con tardanzas repetidas.', 'Llegadas tarde ÷ ingresos esperados × 100; empleados con ≥3 tardanzas ÷ dotación × 100.', 'Intervenir antes del cierre de liquidación, aplicar criterios uniformes y prevenir contaminación del clima.', '%', 'down', 2),
  (v_rrhh, 'Incidencia y días perdidos por ART/licencias', 'Mide frecuencia y severidad de accidentes, ART y licencias médicas, sin exponer información clínica individual.', 'Casos por cada 100 empleados; y días perdidos ÷ dotación promedio.', 'Revisar prevención, ergonomía, cobertura de puestos y concentración de riesgos por área.', 'casos', 'down', 3),
  (v_rrhh, 'Reincidencia disciplinaria y oportunidad de actuación', 'Mide repetición de una conducta luego de apercibimiento o suspensión y cuánto tarda el circuito formal en actuar.', 'Personas con reincidencia en 90 días ÷ personas con medida previa; días entre hecho y resolución.', 'Evaluar efectividad de las medidas y evitar respuestas tardías o inconsistentes.', '%', 'down', 4),
  (v_rrhh, 'Rotación de personal', 'Mide altas y bajas respecto de la dotación promedio, diferenciando salida voluntaria, involuntaria, área y motivo.', 'Bajas del período ÷ dotación promedio × 100.', 'Detectar sectores inestables, evaluar calidad de incorporación y anticipar costos de reemplazo.', '%', 'down', 5),
  (v_rrhh, 'Costo total de personal y costo por área', 'Mide remuneraciones, cargas y beneficios por área y por empleado equivalente a tiempo completo.', 'Sueldos + cargas sociales + beneficios + variables.', 'Presupuestar, comparar estructura con actividad y evaluar capacidad ociosa sin mirar sólo cantidad de personas.', '$', 'up', 6),
  (v_rrhh, 'Costo potencial de desvinculación', 'Estima el pasivo potencial de indemnización para escenarios de decisión, actualizado por antigüedad y conceptos aplicables.', 'Suma de estimaciones individuales vigentes según la metodología aprobada por RRHH y asesores legales.', 'Evaluar escenarios organizativos y necesidades de liquidez antes de tomar decisiones.', '$', 'down', 7),
  (v_rrhh, 'Exposición por anticipos al personal', 'Consolida anticipos de sueldo y beneficios equivalentes frente a la capacidad de recupero.', 'Saldo pendiente de anticipos ÷ masa salarial neta × 100; casos fuera de política y antigüedad del saldo.', 'Proteger caja, evitar múltiples canales de crédito y priorizar excepciones justificadas.', '%', 'down', 8),
  (v_rrhh, 'Costo de incidentes internos atribuibles', 'Mide daños, choques, errores operativos o negligencias con costo para la empresa, por área y causa.', 'Costo de reparación o pérdida atribuible por período; cantidad de incidentes y recurrencia.', 'Corregir procesos, capacitación, custodia de activos y prevención de riesgos.', '$', 'down', 9);

  -- ADM. Y FINANZAS
  INSERT INTO kpis (area_id, name, definition, formula, decision, unit, target_direction, sort_order) VALUES
  (v_finan, 'Liquidez y disponibilidades', 'Expone caja, bancos, inversiones en cauciones y moneda extranjera, con fecha de disponibilidad y fondos comprometidos separados.', 'Disponible utilizable = suma de fondos aplicables al horizonte aprobado. Cobertura = disponible ÷ pagos de ese horizonte.', 'Anticipar restricciones de pago con una foto de fondos utilizables, no sólo con el ratio patrimonial.', '$', 'up', 1),
  (v_finan, 'Endeudamiento total por origen', 'Muestra saldos por RCI, bancos, cheques diferidos negociados, proveedores y otros pasivos, diferenciando deuda financiera y vencimientos.', 'Suma de obligaciones sin duplicación; deuda por origen ÷ deuda total × 100.', 'Priorizar pagos y revisar concentración, vencimientos y respaldo; no reducir todo el endeudamiento a autos debidos.', '$', 'down', 2),
  (v_finan, 'Rentabilidad: margen neto por actividad y total', 'Mide el resultado de VN, VU, RE, SE y PR después de costos, gastos e impuestos asignados; muestra el total de la empresa.', 'Resultado neto de actividad ÷ ingresos netos de actividad × 100. Total = resultado neto empresa ÷ ingresos netos empresa × 100.', 'Identificar actividades deficitarias y evaluar el resultado después de estructura y financiación.', '%', 'up', 3),
  (v_finan, 'Costos de estructura por unidad de negocio y sucursal', 'Expone gastos fijos operativos por rubro, actividad y sucursal, distinguiendo imputaciones directas de gastos comunes distribuidos.', 'Gastos fijos devengados; incidencia = gastos fijos ÷ ingresos netos × 100.', 'Evaluar tamaño y costo de la estructura, evitando confundir menor venta con mayor gasto absoluto.', '$', 'down', 4),
  (v_finan, 'Costos financieros', 'Mide intereses, comisiones y cargos de financiación, por instrumento y origen, con sus tasas y plazos.', 'Intereses + cargos de financiación devengados; incidencia sobre ingresos netos × 100.', 'Relacionar deuda y costo del mes; revisar instrumentos y condiciones de financiación.', '$', 'down', 5),
  (v_finan, 'Días o meses de inventarios: VN, VU y RE', 'Mide cobertura al ritmo reciente de ventas o consumo, con tres resultados separados y la ventana de cálculo informada.', 'Días = inventario al cierre a costo ÷ costo diario promedio de ventas/consumo; meses = inventario a costo ÷ costo mensual promedio.', 'Ajustar compras y salida de stock.', 'días', 'down', 6),
  (v_finan, 'Absorción de Postventa', 'Mide qué proporción de los gastos fijos de toda la empresa cubre la contribución de Repuestos y Servicios.', '(Contribución RE + contribución SE) ÷ gastos fijos operativos totales × 100.', 'Relacionar el aporte de Postventa con la estructura total.', '%', 'up', 7),
  (v_finan, 'Créditos a cobrar', 'Completa la foto patrimonial con cuentas corrientes, trámites de gestoría/patentamiento y liquidaciones de tarjetas pendientes de cobro.', 'Suma de saldos por cobrar sin duplicación; apertura vigente/vencido y fecha esperada de acreditación.', 'Priorizar cobranza y anticipar fondos, distinguiendo ventas realizadas de dinero efectivamente disponible.', '$', 'down', 8);
END $$;